version: '3.9'

services:
  bot:
    build: .
    image: students-crm
    container_name: students-crm-bot
    env_file: .env
    volumes:
      - db-data:/app/db
    restart: unless-stopped

  web:
    image: students-crm
    container_name: students-crm-web
    env_file: .env
    command: ["uv", "run", "--env-file", ".env", "fastapi", "dev", "src/students_crm/webform/main.py", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    depends_on:
      - bot
    volumes:
      - db-data:/app/db
    restart: unless-stopped

volumes:
  db-data:
